{{- if not .Values.tls.certManager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ include "ai-guard.namespace" . }}
  labels:
    {{- include "ai-guard.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "tls.crt is required" .Values.tls.crt | quote }}
  tls.key: {{ required "tls.key is required" .Values.tls.key | quote }}
{{- end }}
