apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-guard.fullname" . }}-webhook
  namespace: {{ include "ai-guard.namespace" . }}
  labels:
    {{- include "ai-guard.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "ai-guard.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: operator
  ports:
    - name: https
      port: 443
      targetPort: https
